export const column = [
  { field: "id", headerName: "ID", width: 50 },
  {
    field: "img",
    headerName: "Image",
    width: 80,
    renderCell: (params) => {
      return <img className="cellImg" src={params.row.img} alt="" />;
    },
  },
  {
    field: "firstName",
    headerName: "First Name",
    width: 120,
  },
  {
    field: "lastName",
    headerName: "Last Name",
    width: 120,
  },

  {
    field: "gender",
    headerName: "Gender",
    width: 120,
  },
  {
    field: "cast",
    headerName: "Cast",
    width: 120,
  },
  {
    field: "address",
    headerName: "Address",
    width: 120,
  },
  {
    field: "school",
    headerName: "School",
    width: 190,
  },
  {
    field: "class",
    headerName: "Class",
    width: 120,
  },
  {
    field: "affidavit",
    headerName: "Affidavit",
    width: 120,
    renderCell: (params) => {
      return (
        <div className={`affidavit ${params.row.affidavit}`}>
          {params.row.affidavit}
        </div>
      );
    },
  },

  {
    field: "isSponsored",
    headerName: "Sponsored",
    width: 120,
    renderCell: (params) => {
      return (
        <div className={`isSponsored ${params.row.isSponsored}`}>
          {params.row.isSponsored}
        </div>
      );
    },
  },
  {
    field: "status",
    headerName: "Status",
    width: 120,
    renderCell: (params) => {
      return (
        <div className={`status ${params.row.status}`}>{params.row.status}</div>
      );
    },
  },
];
export const orphancolumn = [
  { field: "id", headerName: "ID", width: 50 },

  {
    field: "firstName",
    headerName: "First Name",
    width: 90,
  },
  {
    field: "lastName",
    headerName: "Last Name",
    width: 90,
  },
  {
    field: "fatherName",
    headerName: "Father Name",
    width: 100,
  },
  {
    field: "motherName",
    headerName: "Mother Name",
    width: 100,
  },

  {
    field: "address",
    headerName: "Address",
    width: 100,
  },
  {
    field: "school",
    headerName: "School",
    width: 120,
  },
  {
    field: "class",
    headerName: "Class",
    width: 60,
  },
  {
    field: "siblings",
    headerName: "Siblings",
    width: 70,
  },
  {
    field: "refName",
    headerName: "Ref Name",
    width: 90,
  },
  {
    field: "refRelation",
    headerName: "Ref Relation",
    width: 90,
  },
  {
    field: "refContact",
    headerName: "Ref Contact",
    width: 90,
  },
  {
    field: "joiningDate",
    headerName: "Joining Date",
    width: 100,
  },
  {
    field: "leavingDate",
    headerName: "Leaving Date",
    width: 100,
  },
  {
    field: "leavingReason",
    headerName: "Leaving Reason",
    width: 100,
  },
];

export const row = [
  {
    id: 1,
    firstName: "Ali",
    lastName: "Jan",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    age: 12,
    fatherName: "Gulzar",
    motherName: "Razia",
    DOB: "01-03-2015",
    gender: "Male",
    cast: "Syed",
    address: "Sibi",
    school: "Allied Public School",
    class: 4,
    siblings: 2,
    affidavit: "Yes",
    refName: "Fazal",
    refContact: "0333-6068148",
    refRelation: "Uncle",
    isSponsored: "Yes",
    status: "Active",
    joiningDate: "01-01-2022",
    leavingDate: "01-01-2023",
    leavingReason: "food",
  },
  {
    id: 2,
    firstName: "Ahsaan",
    lastName: "Raees",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    age: 13,
    fatherName: "Sultan Ali",
    motherName: "Fatima Ali",
    DOB: "01-03-2015",
    gender: "Male",
    cast: "Khan",
    address: "Ali Pur",
    school: "Allied Public School",
    class: 4,
    siblings: 2,
    affidavit: "Yes",
    refName: "Mohammad",
    refContact: "0333-6065248",
    refRelation: "Uncle",
    isSponsored: "No",
    status: "Pending",
    joiningDate: "01-01-2022",
    leavingDate: "01-01-2023",
    leavingReason: "food",
  },
  {
    id: 3,
    firstName: "Qasim",
    lastName: "Noman",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    age: 12,
    fatherName: "Mujtaba",
    motherName: "Ayesha",
    DOB: "01-03-2015",
    gender: "Male",
    cast: "Kharal",
    address: "Bhawalpur",
    school: "Allied Public School",
    class: 4,
    siblings: 2,
    affidavit: "Yes",
    refName: "Fazal",
    refContact: "0333-6068148",
    refRelation: "Uncle",
    isSponsored: "Yes",
    status: "Left",
    joiningDate: "01-01-2022",
    leavingDate: "01-01-2023",
    leavingReason: "food",
  },
  {
    id: 4,
    firstName: "Muhmmad",
    lastName: "Taqi",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    age: 12,
    fatherName: "Rasool Baksh",
    motherName: "Rizwana Bibi",
    DOB: "01-03-2015",
    gender: "Male",
    cast: "Syed",
    address: "Toba",
    school: "Allied Public School",
    class: 6,
    siblings: 1,
    affidavit: "Yes",
    refName: "Fazal",
    refContact: "0333-6068148",
    refRelation: "Uncle",
    isSponsored: "No",
    status: "Active",
    joiningDate: "01-01-2022",
    leavingDate: "01-01-2023",
    leavingReason: "food",
  },
  {
    id: 5,
    firstName: "Muhammad",
    lastName: "Ali",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    age: 12,
    fatherName: "Rasool Baksh",
    motherName: "Rizwana Bibi",
    DOB: "01-03-2015",
    gender: "Male",
    cast: "Syed",
    address: "Toba",
    school: "Allied Public School",
    class: 4,
    siblings: 1,
    affidavit: "Yes",
    refName: "Adv Waseem Baloch",
    refContact: "0333-4704812",
    refRelation: "Uncle",
    isSponsored: "Yes",
    status: "Pending",
    joiningDate: "01-01-2022",
    leavingDate: "01-01-2023",
    leavingReason: "food",
  },
  {
    id: 6,
    firstName: "Taskeen",
    lastName: "Ali",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    age: 12,
    fatherName: "Hammad",
    motherName: "Saba",
    DOB: "01-03-2015",
    gender: "Male",
    cast: "baloch",
    school: "Allied Public School",
    class: 4,
    address: "Khanewal",
    siblings: 2,
    affidavit: "Yes",
    refName: "Abis",
    refContact: "0333-6068148",
    refRelation: "Uncle",
    isSponsored: "No",
    status: "Active",
    joiningDate: "01-01-2022",
    leavingDate: "01-01-2023",
    leavingReason: "food",
  },
  {
    id: 7,
    firstName: "Waseem",
    lastName: "Nabi",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    age: 12,
    fatherName: "Adnan",
    motherName: "Raziz",
    DOB: "01-03-2015",
    gender: "Male",
    cast: "butta",
    address: "Rasoolpur",
    school: "Allied Public School",
    class: 4,
    siblings: 2,
    affidavit: "Yes",
    refName: "Fazal",
    refContact: "0333-6068148",
    refRelation: "Uncle",
    isSponsored: "Yes",
    status: "Pending",
    joiningDate: "01-01-2022",
    leavingDate: "01-01-2023",
    leavingReason: "food",
  },
  {
    id: 8,
    firstName: "Afzal",
    lastName: "zahoor",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    age: 12,
    fatherName: "Sajid",
    motherName: "Sultana",
    DOB: "01-03-2015",
    gender: "Male",
    cast: "Syed",
    address: "Kabirwala",
    school: "Allied Public School",
    class: 4,
    siblings: 2,
    affidavit: "No",
    refName: "Sultan",
    refContact: "0333-4158148",
    refRelation: "Uncle",
    isSponsored: "Yes",
    status: "Active",
    joiningDate: "01-01-2022",
    leavingDate: "01-01-2023",
    leavingReason: "food",
  },
  {
    id: 9,
    firstName: "Asad",
    lastName: "Shah",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    age: 12,
    fatherName: "Asif",
    motherName: "Maria",
    DOB: "01-03-2015",
    gender: "Male",
    cast: "Syed",
    address: "MuzaffarGarh",
    school: "Allied Public School",
    class: 4,
    siblings: 2,
    affidavit: "Yes",
    refName: "Fazal",
    refContact: "0333-6068148",
    refRelation: "Uncle",
    isSponsored: "No",
    status: "Active",
    joiningDate: "01-01-2022",
    leavingDate: "01-01-2023",
    leavingReason: "food",
  },
  {
    id: 10,
    firstName: "Bilal",
    lastName: "Danish",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    age: 12,
    fatherName: "Darain",
    motherName: "Asia",
    DOB: "01-03-2015",
    gender: "Male",
    cast: "Baloch",
    address: "qadirpur",
    school: "Allied Public School",
    class: 4,
    siblings: 2,
    affidavit: "Yes",
    refName: "Fazal",
    refContact: "0333-6068148",
    refRelation: "Uncle",
    isSponsored: "Yes",
    status: "Active",
    joiningDate: "01-01-2022",
    leavingDate: "01-01-2023",
    leavingReason: "food",
  },
  {
    id: 11,
    firstName: "Ali",
    lastName: "Jan",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    age: 12,
    fatherName: "Gulzar",
    motherName: "Razia",
    DOB: "01-03-2015",
    gender: "Male",
    cast: "Syed",
    school: "Allied Public School",
    class: 4,
    siblings: 2,
    affidavit: "Yes",
    refName: "Fazal",
    refContact: "0333-6068148",
    refRelation: "Uncle",
    isSponsored: "Yes",
    status: "Active",
    joiningDate: "01-01-2022",
    leavingDate: "01-01-2023",
    leavingReason: "food",
  },
  {
    id: 12,
    firstName: "Ali",
    lastName: "Jan",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    age: 12,
    fatherName: "Gulzar",
    motherName: "Razia",
    DOB: "01-03-2015",
    gender: "Male",
    cast: "Syed",
    school: "Allied Public School",
    class: 4,
    siblings: 2,
    affidavit: "Yes",
    refName: "Fazal",
    refContact: "0333-6068148",
    refRelation: "Uncle",
    isSponsored: "Yes",
    status: "Pending",
    joiningDate: "01-01-2022",
    leavingDate: "01-01-2023",
    leavingReason: "food",
  },
  {
    id: 13,
    firstName: "Ali",
    lastName: "Jan",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    age: 12,
    fatherName: "Gulzar",
    motherName: "Razia",
    DOB: "01-03-2015",
    gender: "Male",
    cast: "Syed",
    school: "Allied Public School",
    class: 4,
    siblings: 2,
    affidavit: "Yes",
    refName: "Fazal",
    refContact: "0333-6068148",
    refRelation: "Uncle",
    isSponsored: "Yes",
    status: "Active",
    joiningDate: "01-01-2022",
    leavingDate: "01-01-2023",
    leavingReason: "food",
  },
  {
    id: 14,
    firstName: "Ali",
    lastName: "Jan",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    age: 12,
    fatherName: "Gulzar",
    motherName: "Razia",
    DOB: "01-03-2015",
    gender: "Male",
    cast: "Syed",
    school: "Allied Public School",
    class: 4,
    siblings: 2,
    affidavit: "Yes",
    refName: "Fazal",
    refContact: "0333-6068148",
    refRelation: "Uncle",
    isSponsored: "Yes",
    status: "Active",
    joiningDate: "01-01-2022",
    leavingDate: "01-01-2023",
    leavingReason: "food",
  },
  {
    id: 15,
    firstName: "Ali",
    lastName: "Jan",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    age: 12,
    fatherName: "Gulzar",
    motherName: "Razia",
    DOB: "01-03-2015",
    gender: "Male",
    cast: "Syed",
    school: "Allied Public School",
    class: 4,
    siblings: 2,
    affidavit: "Yes",
    refName: "Fazal",
    refContact: "0333-6068148",
    refRelation: "Uncle",
    isSponsored: "Yes",
    status: "Pending",
    joiningDate: "01-01-2022",
    leavingDate: "01-01-2023",
    leavingReason: "food",
  },
  {
    id: 16,
    firstName: "Ali",
    lastName: "Jan",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    age: 12,
    fatherName: "Gulzar",
    motherName: "Razia",
    DOB: "01-03-2015",
    gender: "Male",
    cast: "Syed",
    school: "Allied Public School",
    class: 4,
    siblings: 2,
    affidavit: "Yes",
    refName: "Fazal",
    refContact: "0333-6068148",
    refRelation: "Uncle",
    isSponsored: "Yes",
    status: "Left",
    joiningDate: "01-01-2022",
    leavingDate: "01-01-2023",
    leavingReason: "food",
  },
  {
    id: 17,
    firstName: "Ali",
    lastName: "Jan",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    age: 12,
    fatherName: "Gulzar",
    motherName: "Razia",
    DOB: "01-03-2015",
    gender: "Male",
    cast: "Syed",
    school: "Allied Public School",
    class: 4,
    siblings: 2,
    affidavit: "Yes",
    refName: "Fazal",
    refContact: "0333-6068148",
    refRelation: "Uncle",
    isSponsored: "Yes",
    status: "Left",
    joiningDate: "01-01-2022",
    leavingDate: "01-01-2023",
    leavingReason: "food",
  },
  {
    id: 18,
    firstName: "Ali",
    lastName: "Jan",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    age: 12,
    fatherName: "Gulzar",
    motherName: "Razia",
    DOB: "01-03-2015",
    gender: "Male",
    cast: "Syed",
    school: "Allied Public School",
    class: 4,
    siblings: 2,
    affidavit: "Yes",
    refName: "Fazal",
    refContact: "0333-6068148",
    refRelation: "Uncle",
    isSponsored: "Yes",
    status: "Active",
    joiningDate: "01-01-2022",
    leavingDate: "01-01-2023",
    leavingReason: "food",
  },
  {
    id: 19,
    firstName: "Kashif",
    lastName: "Mehmood",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    age: 12,
    fatherName: "Muhmmad",
    motherName: "Faiqa",
    DOB: "01-03-2015",
    gender: "Male",
    cast: "Khan",
    school: "Divisional Public School",
    class: 6,
    siblings: 0,
    affidavit: "No",
    refName: "Jawad",
    refContact: "0333-5254148",
    refRelation: "Nieghbour",
    isSponsored: "No",
    status: "Left",
    joiningDate: "01-01-2022",
    leavingDate: "01-01-2023",
    leavingReason: "food",
  },
];
export const sponsorColumn = [
  { field: "id", headerName: "ID", width: 70 },
  {
    field: "img",
    headerName: "Image",
    width: 70,
    renderCell: (params) => {
      return (
        <div className="cellwithImg">
          <img src={params.row.img} className="cellImg" alt="" />
        </div>
      );
    },
  },
  {
    field: "name",
    headerName: "Name",
    width: 140,
  },
  {
    field: "phone",
    headerName: "Phone",
    width: 140,
  },
  {
    field: "email",
    headerName: "Email",
    width: 220,
  },
  {
    field: "gender",
    headerName: "Gender",
    width: 80,
  },
  {
    field: "address",
    headerName: "Address",
    width: 80,
  },
  {
    field: "city",
    headerName: "City",
    width: 80,
  },
  {
    field: "province",
    headerName: "Province",
    width: 80,
  },
  {
    field: "country",
    headerName: "Country",
    width: 80,
  },
  {
    field: "adoptedCount",
    headerName: "Adopted Count",
    width: 120,
  },
  {
    field: "refSource",
    headerName: "Ref Source",
    width: 120,
  },
  {
    field: "status",
    headerName: "Status",
    width: 120,
    renderCell: (params) => {
      return (
        <div className={`cellWithStatus ${params.row.status}`}>
          {params.row.status}
        </div>
      );
    },
  },
];
export const sponsorRow = [
  {
    id: 1,
    name: "Ali Jan",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "alijan@idaraekhudi.com",
    phone: "0333-5252125",
    gender: "Male",
    address: "Sibi",
    city: "Multan",
    province: "punjab",
    country: "Pakistan",
    adoptedCount: 2,
    refSource: "Social media",
    status: "Active",
  },
  {
    id: 2,
    name: "Ahsan Raees",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",

    email: "ahsanraees@idaraekhudi.com",
    gender: "Male",
    address: "Ali Pur",
    city: "Multan",
    province: "punjab",
    country: "Pakistan",
    adoptedCount: 4,
    refSource: "Social media",
    status: "Pending",
  },
  {
    id: 3,
    name: "Fatima Sugra",

    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",

    email: "Qasimshuja@idaraekhudi.com",

    gender: "Female",

    address: "Bhawalpur",

    city: "Multan",
    province: "punjab",
    country: "Pakistan",
    adoptedCount: 2,
    refSource: "Social media",
    status: "Passive",
  },
  {
    id: 4,
    name: "Qasim Shuja",

    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",

    email: "Qasimshuja@idaraekhudi.com",

    gender: "Male",

    address: "Bhawalpur",
    city: "Multan",
    province: "punjab",
    country: "Pakistan",
    adoptedCount: 2,
    refSource: "Social media",
    status: "Active",
  },
  {
    id: 5,
    name: "Muhmmad Taqi",

    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",

    email: "Mtaqi@idaraekhudi.com",

    gender: "Male",

    address: "Toba",

    city: "Multan",
    province: "punjab",
    country: "Pakistan",
    adoptedCount: 2,
    refSource: "Social media",
    status: "Pending",
  },
  {
    id: 6,
    name: "Muhammad khan",

    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",

    email: "Mkhan@idaraekhudi.com",
    gender: "Male",

    address: "Toba",
    city: "Multan",
    province: "punjab",
    country: "Pakistan",
    adoptedCount: 1,
    refSource: "Social media",
    status: "Active",
  },
  {
    id: 7,
    name: "Ali Jan",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "alijan@idaraekhudi.com",
    phone: "0333-5252125",
    gender: "Male",
    address: "Sibi",
    city: "Multan",
    province: "punjab",
    country: "Pakistan",
    adoptedCount: 2,
    refSource: "Social media",
    status: "Active",
  },
  {
    id: 8,
    name: "Ahsan Raees",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",

    email: "ahsanraees@idaraekhudi.com",
    gender: "Male",
    address: "Ali Pur",
    city: "Multan",
    province: "punjab",
    country: "Pakistan",
    adoptedCount: 4,
    refSource: "Social media",
    status: "Pending",
  },
  {
    id: 9,
    name: "Fatima Sugra",

    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",

    email: "Qasimshuja@idaraekhudi.com",

    gender: "Female",

    address: "Bhawalpur",

    city: "Multan",
    province: "punjab",
    country: "Pakistan",
    adoptedCount: 2,
    refSource: "Social media",
    status: "Active",
  },
  {
    id: 10,
    name: "Qasim Shuja",

    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",

    email: "Qasimshuja@idaraekhudi.com",

    gender: "Male",

    address: "Bhawalpur",
    city: "Multan",
    province: "punjab",
    country: "Pakistan",
    adoptedCount: 2,
    refSource: "Social media",
    status: "Active",
  },
  {
    id: 11,
    name: "Muhmmad Taqi",

    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",

    email: "Mtaqi@idaraekhudi.com",

    gender: "Male",

    address: "Toba",

    city: "Multan",
    province: "punjab",
    country: "Pakistan",
    adoptedCount: 2,
    refSource: "Social media",
    status: "Pending",
  },
  {
    id: 12,
    name: "Muhammad khan",

    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",

    email: "Mkhan@idaraekhudi.com",
    gender: "Male",

    address: "Toba",
    city: "Multan",
    province: "punjab",
    country: "Pakistan",
    adoptedCount: 1,
    refSource: "Social media",
    status: "Active",
  },
  {
    id: 13,
    name: "Ali Jan",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "alijan@idaraekhudi.com",
    phone: "0333-5252125",
    gender: "Male",
    address: "Sibi",
    city: "Multan",
    province: "punjab",
    country: "Pakistan",
    adoptedCount: 2,
    refSource: "Social media",
    status: "Pending",
  },
  {
    id: 14,
    name: "Ahsan Raees",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",

    email: "ahsanraees@idaraekhudi.com",
    gender: "Male",
    address: "Ali Pur",
    city: "Multan",
    province: "punjab",
    country: "Pakistan",
    adoptedCount: 4,
    refSource: "Social media",
    status: "Active",
  },
  {
    id: 15,
    name: "Fatima Sugra",

    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",

    email: "Qasimshuja@idaraekhudi.com",

    gender: "Female",

    address: "Bhawalpur",

    city: "Multan",
    province: "punjab",
    country: "Pakistan",
    adoptedCount: 2,
    refSource: "Social media",
    status: "Pending",
  },
  {
    id: 16,
    name: "Qasim Shuja",

    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",

    email: "Qasimshuja@idaraekhudi.com",

    gender: "Male",

    address: "Bhawalpur",
    city: "Multan",
    province: "punjab",
    country: "Pakistan",
    adoptedCount: 2,
    refSource: "Social media",
    status: "Active",
  },
  {
    id: 17,
    name: "Muhmmad Taqi",

    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",

    email: "Mtaqi@idaraekhudi.com",

    gender: "Male",

    address: "Toba",

    city: "Multan",
    province: "punjab",
    country: "Pakistan",
    adoptedCount: 2,
    refSource: "Social media",
    status: "Pending",
  },
  {
    id: 18,
    name: "Muhammad khan",

    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",

    email: "Mkhan@idaraekhudi.com",
    gender: "Male",

    address: "Toba",
    city: "Multan",
    province: "punjab",
    country: "Pakistan",
    adoptedCount: 1,
    refSource: "Social media",
    status: "Active",
  },
  {
    id: 19,
    name: "Ali Jan",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "alijan@idaraekhudi.com",
    phone: "0333-5252125",
    gender: "Male",
    address: "Sibi",
    city: "Multan",
    province: "punjab",
    country: "Pakistan",
    adoptedCount: 2,
    refSource: "Social media",
    status: "Pending",
  },
  {
    id: 20,
    name: "Ahsan Raees",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",

    email: "ahsanraees@idaraekhudi.com",
    gender: "Male",
    address: "Ali Pur",
    city: "Multan",
    province: "punjab",
    country: "Pakistan",
    adoptedCount: 4,
    refSource: "Social media",
    status: "Active",
  },
  {
    id: 21,
    name: "Fatima Sugra",

    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",

    email: "Qasimshuja@idaraekhudi.com",

    gender: "Female",

    address: "Bhawalpur",

    city: "Multan",
    province: "punjab",
    country: "Pakistan",
    adoptedCount: 2,
    refSource: "Social media",
    status: "Pending",
  },
  {
    id: 22,
    name: "Qasim Shuja",

    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",

    email: "Qasimshuja@idaraekhudi.com",

    gender: "Male",

    address: "Bhawalpur",
    city: "Multan",
    province: "punjab",
    country: "Pakistan",
    adoptedCount: 2,
    refSource: "Social media",
    status: "Active",
  },
  {
    id: 23,
    name: "Muhmmad Taqi",

    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",

    email: "Mtaqi@idaraekhudi.com",

    gender: "Male",

    address: "Toba",

    city: "Multan",
    province: "punjab",
    country: "Pakistan",
    adoptedCount: 2,
    refSource: "Social media",
    status: "Active",
  },
  {
    id: 24,
    name: "Muhammad khan",

    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",

    email: "Mkhan@idaraekhudi.com",
    gender: "Male",

    address: "Toba",
    city: "Multan",
    province: "punjab",
    country: "Pakistan",
    adoptedCount: 1,
    refSource: "Social media",
    status: "Pending",
  },
];
export const branchesColumn = [
  { field: "id", headerName: "ID", width: 70 },
  {
    field: "brname",
    headerName: "Branch Name",
    width: 120,
  },
  {
    field: "brCity",
    headerName: "Branch City",
    width: 120,
  },
  {
    field: "brProvince",
    headerName: "Branch Province",
    width: 120,
  },
  {
    field: "brAddress",
    headerName: "Branch Address",
    width: 140,
  },
  {
    field: "adminName",
    headerName: "Admin Name",
    width: 120,
  },
  {
    field: "adminContact",
    headerName: "Admin Contact",
    width: 120,
  },
  {
    field: "adminEmail",
    headerName: "Admin Email",
    width: 180,
  },
];
export const branchesRow = [
  {
    id: 1,
    brname: "Hamdard House",
    brCity: "Multan",
    brProvince: "Punjab",
    brAddress: "Gulgasht Multan",
    adminName: "Zafar Kazmi",
    adminContact: "0333-4525142",
    adminEmail: "zafar-kazmi@gmail.com",
  },
  {
    id: 2,
    brname: "Fatima House",
    brCity: "Multan",
    brProvince: "Punjab",
    brAddress: "Green Lane Multan",
    adminName: "Ruqaiya Fatima",
    adminContact: "0333-4525142",
    adminEmail: "Ruqaiya Fatima@gmail.com",
  },
  {
    id: 3,
    brname: "Baqiatul Allah",
    brCity: "Lahore",
    brProvince: "Punjab",
    brAddress: "Faisal town Lahore",
    adminName: "Zain Ali",
    adminContact: "0333-4525142",
    adminEmail: "ZainAli@gmail.com",
  },
];
